### Boolean masking

In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [12]:
df= pd.read_csv("netflix_titles_2021 (1).csv")
df.sample(10)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
4264,s4265,TV Show,People Just Do Nothing,NaN,"Allan Mustafa, Hugo Chegwin, Asim Chaudhry, Li...",United Kingdom,"December 22, 2018",2018,TV-MA,5 Seasons,"British TV Shows, TV Comedies",Spinning old-school beats is just another day ...
5505,s5506,Movie,Loev,Sudhanshu Saria,"Shiv Pandit, Dhruv Ganesh, Siddharth Menon, Ri...",India,"May 1, 2017",2015,TV-MA,89 min,"Dramas, Independent Movies, International Movies",Lives are upended when a hiking trip leads a W...
3413,s3414,Movie,Verses of Love 2,Guntur Soeharjanto,"Fedi Nuril, Tatjana Saphira, Dewi Sandra, Chel...",Indonesia,"October 18, 2019",2017,TV-14,127 min,"Dramas, Faith & Spirituality, International Mo...","Now a lecturer in Edinburgh, Fahri tries to be..."
6676,s6677,TV Show,El Clon,NaN,"Mauricio Ochmann, Sandra Echeverría, Saúl Lisa...",United States,"May 18, 2017",2010,TV-14,1 Season,"Romantic TV Shows, Spanish-Language TV Shows, ...",Religion thwarted Lucas and Jade's young love....
2795,s2796,TV Show,"Tiger King: Murder, Mayhem and Madness","Eric Goode, Rebecca Chaiklin",NaN,United States,"March 20, 2020",2020,TV-MA,1 Season,"Crime TV Shows, Docuseries",A zoo owner spirals out of control amid a cast...
948,s949,Movie,Swiped,Ann Deborah Fishman,"Kendall Ryan Sanders, Noah Centineo, Nathan Ga...",United States,"May 1, 2021",2018,TV-14,94 min,Comedies,When two college roommates develop a discreet ...
4348,s4349,Movie,SDU: Sex Duties Unit,Gary Mak,"Chapman To, Shawn Yue, Matt Chow, Kwok Cheung ...",Hong Kong,"December 1, 2018",2013,TV-MA,96 min,"Comedies, International Movies",Four man-children in an elite tactical unit ga...
5162,s5163,Movie,Saving Capitalism,Jacob Kornbluth,Robert Reich,United States,"November 21, 2017",2017,TV-PG,73 min,Documentaries,Former Secretary of Labor Robert Reich meets w...
1548,s1549,TV Show,The Challenge,NaN,"Jamie Chung, Landon Lueck, Diem Brown, Mike 'T...",United States,"December 15, 2020",2006,TV-14,2 Seasons,Reality TV,Reality show alumni must compete in grueling p...
3932,s3933,Movie,Sarvam Thaala Mayam (Telugu Version),Rajiv Menon,"G.V. Prakash Kumar, Nedumudi Venu, Aparna Bala...",India,"April 8, 2019",2018,TV-14,131 min,"Dramas, International Movies, Music & Musicals",An aspiring musician battles age-old caste div...

In [3]:
df['release_year']

0       2020
1       2021
2       2021
3       2021
4       2021
        ...
8802    2007
8803    2018
8804    2009
8805    2006
8806    2015
Name: release_year, Length: 8807, dtype: int64

# Boolean masking

In [24]:
release_year=pd.Series([2020,2021,2021,2020,2018,2019,2015,2022])
BM=[True,False,True,True,False,False,True,False]
release_year[BM]

0    2020
2    2021
3    2020
6    2015
dtype: int64

In [21]:
df2=df.query('release_year==2020&type=="Movie"')
df2.head(10)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
16,s17,Movie,Europe's Most Dangerous Man: Otto Skorzeny in ...,"Pedro de Echave García, Pablo Azorín Williams",NaN,NaN,"September 22, 2021",2020,TV-MA,67 min,"Documentaries, International Movies",Declassified documents reveal the post-WWII li...
78,s79,Movie,Tughlaq Durbar,Delhiprasad Deenadayalan,"Vijay Sethupathi, Parthiban, Raashi Khanna",NaN,"September 11, 2021",2020,TV-14,145 min,"Comedies, Dramas, International Movies",A budding politician has devious plans to rise...
84,s85,Movie,Omo Ghetto: the Saga,"JJC Skillz, Funke Akindele","Funke Akindele, Ayo Makun, Chioma Chukwuka Akp...",Nigeria,"September 10, 2021",2020,TV-MA,147 min,"Action & Adventure, Comedies, Dramas",Twins are reunited as a good-hearted female ga...
103,s104,Movie,Shadow Parties,Yemi Amodu,"Jide Kosoko, Omotola Jalade-Ekeinde, Yemi Blaq...",NaN,"September 6, 2021",2020,TV-MA,117 min,"Dramas, International Movies, Thrillers",A family faces destruction in a long-running c...
119,s120,Movie,Here and There,JP Habac,"Janine Gutierrez, JC Santos, Victor Anastacio,...",NaN,"September 2, 2021",2020,TV-MA,99 min,"Dramas, International Movies, Romantic Movies",After meeting through a heated exchange on soc...
126,s127,Movie,Shikara,Vidhu Vinod Chopra,"Aadil Khan, Sadia Khateeb, Zain Khan Durrani, ...",India,"September 2, 2021",2020,TV-14,115 min,"Dramas, International Movies, Romantic Movies",A couple must strive to remain resilient after...
227,s228,Movie,Really Love,Angel Kristi Williams,"Kofi Siriboe, Yootha Wong-Loi-Sing, Michael Ea...",United States,"August 25, 2021",2020,TV-MA,95 min,"Dramas, Independent Movies, Romantic Movies",A rising Black painter tries to break into a c...
229,s230,Movie,The Old Ways,Christopher Alender,"Brigitte Kali Canales, Andrea Cortes, Julia Ve...",United States,"August 25, 2021",2020,TV-MA,90 min,Horror Movies,A reporter visits her birthplace in Veracruz f...
250,s251,Movie,A Faraway Land,Veronica Velasco,"Paolo Contis, Yen Santos, Hans Tórgarð, Ruby R...",NaN,"August 19, 2021",2020,TV-PG,102 min,"Dramas, International Movies, Romantic Movies","In the Faroe Islands, a married woman meets a ..."

#### display the count of movies released in the year 2020 in nation

In [31]:
BM = df.release_year==2020

In [26]:
df[BM].country.value_counts()

United States                             336
India                                      75
United Kingdom                             44
South Korea                                28
Canada                                     26
                                         ...
Germany, Czech Republic                     1
United States, Bulgaria                     1
United Kingdom, France, Germany, Spain      1
Thailand, United States                     1
United States, South Korea, China           1
Name: country, Length: 107, dtype: int64

In [27]:
BM = df.release_year <= 1990

In [28]:
df[BM].country.value_counts()

United States                                                  120
India                                                           49
Hong Kong                                                       20
Egypt                                                           11
Poland                                                           7
United Kingdom                                                   6
United States, United Kingdom                                    5
United Kingdom, United States                                    5
Japan                                                            3
Argentina                                                        2
Italy, United States                                             2
Australia, United States                                         2
Lebanon, Canada, France                                          2
Hong Kong, China                                                 1
Hong Kong, United States                                         1
Poland,                                                          1
France                                                           1
United States, Japan                                             1
Poland, West Germany                                             1
Italy, France                                                    1
Mexico                                                           1
Italy                                                            1
United States, Canada                                            1
United States, East Germany, West Germany                        1
Italy, South Africa, West Germany, Australia, United States      1
India, Soviet Union                                              1
United States, Italy, United Kingdom, Liechtenstein              1
Ireland, United Kingdom, United States                           1
Denmark, France, Poland                                          1
West Germany                                                     1
India, Malaysia                                                  1
Soviet Union, India                                              1
United Kingdom, West Germany                                     1
Kuwait                                                           1
France, Egypt                                                    1
Egypt, Algeria                                                   1
United States, Mexico                                            1
France, Lebanon                                                  1
Lebanon                                                          1
Australia                                                        1
Name: country, dtype: int64

In [29]:
df.rating.unique()

array(['PG-13', 'TV-MA', 'PG', 'TV-14', 'TV-PG', 'TV-Y', 'TV-Y7', 'R',
       'TV-G', 'G', 'NC-17', '74 min', '84 min', '66 min', 'NR', nan,
       'TV-Y7-FV', 'UR'], dtype=object)

In [30]:
df.type.unique()

array(['Movie', 'TV Show'], dtype=object)

### count of movies released in each year

In [51]:
BM=df.type=="Movie"

In [52]:
df[BM].release_year.value_counts()

2017    767
2018    767
2016    658
2019    633
2020    517
       ...
1966      1
1961      1
1946      1
1963      1
1947      1
Name: release_year, Length: 73, dtype: int64

In [58]:
BM = (df['type'] == "movie") & (df['release_year'] > 2020)

In [60]:
df[BM].country.value_counts()

Series([], Name: country, dtype: int64)